name: KingdomsAddon
version: ${project.version}
main: su.brim.kingdoms.KingdomsAddon
api-version: '1.21'
folia-supported: true
description: Standalone kingdoms plugin for Folia servers with ghost system
author: Brim
website: https://github.com/Whitebrim
softdepend:
  - TAB
  - PlaceholderAPI
  - GSit

commands:
  kingdoms:
    description: Main command for KingdomsAddon
    usage: /<command> <subcommand> [args]
    aliases: [kd, kingdom]

permissions:
  kingdoms.admin:
    description: Full admin access to KingdomsAddon
    default: op
    children:
      kingdoms.setspawn: true
      kingdoms.reload: true
      kingdoms.assign: true
      kingdoms.info: true
      kingdoms.admin: true
  kingdoms.admin:
    description: Bypass kingdom assignment, ghost system, and damage modifiers
    default: op
  kingdoms.setspawn:
    description: Allows setting kingdom spawn points
    default: op
  kingdoms.reload:
    description: Allows reloading the plugin configuration
    default: op
  kingdoms.assign:
    description: Allows manually assigning players to kingdoms
    default: op
  kingdoms.info:
    description: View information about kingdoms and players
    default: op
